import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle, CirclesThreePlus, Code, Copy, Database, FileCode, Folder, GearSix, Graph, LockSimple, MagnifyingGlass, Pulse, ShieldCheck, Sparkle } from "@phosphor-icons/react";
import { Background, Controls, Handle, MarkerType, Position, ReactFlow } from "@xyflow/react";
import "@xyflow/react/dist/style.css";

const demoProjects = [
  { name: "payments-api", description: "Checkout, payments, and webhook endpoints", languages: ["Go"], dependencies: ["shared-libs"], file_count: 432 },
  { name: "webhook-worker", description: "Asynchronous webhook event processing", languages: ["Go"], dependencies: ["payments-api", "shared-libs"], file_count: 218 },
  { name: "frontend-app", description: "Customer checkout experience", languages: ["TypeScript", "React"], dependencies: ["payments-api"], file_count: 781 },
  { name: "fraud-model", description: "Fraud scoring and payment risk models", languages: ["Python"], dependencies: ["shared-libs"], file_count: 164 },
  { name: "ledger-service", description: "Ledger entries and reconciliation", languages: ["Java"], dependencies: ["payments-api"], file_count: 286 },
  { name: "event-router", description: "Event routing and delivery", languages: ["Rust"], dependencies: ["webhook-worker"], file_count: 129 },
  { name: "billing-api", description: "Subscriptions and invoices", languages: [".NET", "C#"], dependencies: ["payments-api"], file_count: 243 },
  { name: "catalog-service", description: "Product catalog and pricing", languages: ["PHP"], dependencies: ["shared-libs"], file_count: 192 },
  { name: "notification-service", description: "Notification delivery and alerts", languages: ["Ruby"], dependencies: ["webhook-worker"], file_count: 137 },
  { name: "shared-libs", description: "Shared schemas and retry utilities", languages: ["TypeScript"], dependencies: [], file_count: 146 },
];
const demoRoute = { mode: "local_retrieval_only", decision_provider: "local", provider_status: "not_called", primary_project: "payments-api", related_projects: ["webhook-worker", "shared-libs"], needs_clarification: false, change_type: "timeout", candidates: [
  { project: "payments-api", description: "Checkout, payments, and webhook endpoints", local_score: 18.4, semantic_score: 0.92, evidence: ["src/webhooks/checkout_handler.ts", "Handles checkout webhook events and retry behavior.", "RetryPolicy is used by checkout processing."] },
  { project: "webhook-worker", description: "Asynchronous webhook event processing", local_score: 13.7, semantic_score: 0.78, evidence: ["src/processor/retry.go", "Consumes failed webhook jobs."] },
  { project: "shared-libs", description: "Shared schemas and retry utilities", local_score: 8.2, semantic_score: 0.64, evidence: ["src/retry/policy.ts", "Defines shared backoff configuration."] },
] };

function score(candidate, candidates) { if (candidate.semantic_score != null) return Math.round(candidate.semantic_score * 100); const best = Math.max(...candidates.map((item) => item.local_score || 0), 1); return Math.round(((candidate.local_score || 0) / best) * 100); }
function RepoNode({ data }) { const Icon = data.primary ? Database : Folder; return <div className={`repo-node ${data.primary ? "primary" : data.related ? "related" : "muted"}`}><Handle type="target" position={Position.Left} /><span className="repo-icon"><Icon size={20} weight="duotone" /></span><span><strong>{data.label}</strong><small>{data.caption}</small></span><Handle type="source" position={Position.Right} /></div>; }
function SignalNode({ data }) { const icons = { understand: MagnifyingGlass, extract: Code, search: Database, rank: Graph, task: Sparkle }; const Icon = icons[data.kind] || Sparkle; return <div className={`signal-node ${data.kind === "task" ? "task" : ""}`}><Handle type="target" position={Position.Left} /><span className="signal-circle"><Icon size={data.kind === "task" ? 24 : 21} weight="duotone" /></span><strong>{data.label}</strong><Handle type="source" position={Position.Right} /></div>; }
const nodeTypes = { repository: RepoNode, signal: SignalNode };

function SignalMap({ route, projects, task }) {
  const primary = route.primary_project; const related = new Set(route.related_projects || []); const candidates = route.candidates || [];
  const nodes = useMemo(() => { const base = [{ id: "task", type: "signal", position: { x: 5, y: 195 }, data: { label: task.length > 44 ? `${task.slice(0, 41)}…` : task, kind: "task" } }]; const analysis = [["Understand intent","understand"],["Extract signals","extract"],["Search workspace","search"],["Rank evidence","rank"]]; analysis.forEach(([label,kind], index) => base.push({ id: `step-${index}`, type: "signal", position: { x: 250, y: 25 + index * 130 }, data: { label, kind } })); const names = [...new Set([...candidates.map((item) => item.project), ...projects.map((item) => item.name)])].slice(0, 5); names.forEach((name, index) => { const project = projects.find((item) => item.name === name); base.push({ id: `repo-${name}`, type: "repository", position: { x: 515, y: 20 + index * 103 }, data: { label: name, caption: project?.description || candidates.find((item) => item.project === name)?.description || "Repository", primary: name === primary, related: related.has(name) } }); }); return base; }, [route, projects, primary, task]);
  const edges = useMemo(() => { const values = []; for (let index = 0; index < 4; index += 1) values.push({ id: `task-step-${index}`, source: "task", target: `step-${index}`, animated: index < 2, style: { stroke: "#2fd3ff", strokeWidth: 2 } }); nodes.filter((node) => node.id.startsWith("repo-")).forEach((node, index) => { const color = node.data.primary ? "#9dff50" : node.data.related ? "#2fd3ff" : "#3b4a5d"; values.push({ id: `step-repo-${index}`, source: `step-${Math.min(index, 3)}`, target: node.id, animated: node.data.primary || node.data.related, style: { stroke: color, strokeWidth: node.data.primary ? 3 : 1.5 }, markerEnd: { type: MarkerType.ArrowClosed, color } }); }); return values; }, [nodes]);
  return <div className="signal-map" aria-label="Workspace signal map"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView minZoom={0.6} maxZoom={1.4} proOptions={{ hideAttribution: true }}><Background color="#223041" gap={28} size={1} /><Controls showInteractive={false} /></ReactFlow></div>;
}

function EvidencePanel({ route, onCopy }) { const candidates = route.candidates || []; return <aside className="evidence-panel"><div className="panel-heading"><div><p className="eyebrow">Evidence</p><h2>Top signals from your workspace</h2></div><span className="privacy"><LockSimple size={14} weight="fill" /> Local only</span></div><div className="evidence-list">{candidates.slice(0, 3).map((candidate, index) => <article className="evidence-item" key={candidate.project}><div className="evidence-title"><FileCode size={19} weight="duotone" /><strong>{candidate.evidence?.[0] || candidate.project}</strong><span className={index === 0 ? "score primary" : "score"}>{score(candidate, candidates)}%</span></div><p>{candidate.evidence?.[1] || candidate.description}</p><div className="code-line"><span>{candidate.project}</span><code>{candidate.evidence?.[2] || "Relevant repository metadata"}</code></div></article>)}</div><button className="primary-action" onClick={onCopy}><Copy size={19} weight="bold" /> Copy agent context</button><p className="action-note">Copies a focused, evidence-backed context for your coding agent.</p></aside>; }

function RouterView({ projects, workspace }) {
  const [task, setTask] = useState("Add retry limits to checkout webhooks"); const [route, setRoute] = useState(demoRoute); const [loading, setLoading] = useState(false); const [copied, setCopied] = useState(false);
  async function runRoute(event) { event?.preventDefault(); if (!task.trim()) return; setLoading(true); try { const response = await fetch("/api/route", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ task }) }); if (!response.ok) throw new Error("Route failed"); setRoute(await response.json()); } catch { setRoute({ ...demoRoute, warnings: ["Demo data shown because the local API is unavailable."] }); } finally { setLoading(false); } }
  async function copyContext() { await navigator.clipboard.writeText(JSON.stringify(route, null, 2)); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
  return <div className="router-view"><header className="workspace-header"><div><p className="eyebrow">{workspace?.project_count || projects.length} repositories indexed</p><h1>Describe the task. <span>Find the repo.</span> Show the evidence.</h1></div><div className="mode-pill"><span /> {route.decision_provider === "local" ? "Local routing" : route.decision_provider}</div></header><form className="task-form" onSubmit={runRoute}><Sparkle size={21} weight="fill" /><input value={task} onChange={(event) => setTask(event.target.value)} aria-label="Describe the engineering task" /><button type="submit" disabled={loading} aria-label="Route task">{loading ? <Pulse className="spin" size={20} /> : <ArrowRight size={22} weight="bold" />}</button></form>{route.warnings?.length > 0 && <div className="warning-strip">{route.warnings[0]}</div>}<div className="router-layout"><section className="map-column"><div className="map-meta"><span><Graph size={17} /> Workspace signal map</span><div className="legend"><i className="cyan" /> Analysis <i className="lime" /> Primary <i className="blue" /> Related</div></div><SignalMap route={route} projects={projects.length ? projects : demoProjects} task={task} /></section><EvidencePanel route={route} onCopy={copyContext} /></div>{copied && <div className="toast"><CheckCircle size={18} weight="fill" /> Agent context copied</div>}</div>;
}

function RepositoriesView({ projects }) { const values = projects.length ? projects : demoProjects; return <section className="content-view"><div className="content-heading"><div><p className="eyebrow">Workspace</p><h1>Repositories</h1></div><span>{values.length} indexed projects</span></div><div className="project-grid">{values.map((project) => <article className="project-row" key={project.name}><span className="project-mark"><Folder size={22} weight="duotone" /></span><div><h3>{project.name}</h3><p>{project.description || "No description yet"}</p><small>{(project.languages || []).join(" · ") || "Language not detected"}</small></div><div className="project-stats"><strong>{project.file_count || 0}</strong><span>files</span><strong>{project.dependencies?.length || 0}</strong><span>links</span></div></article>)}</div></section>; }
function EvaluationView() { return <section className="content-view"><div className="content-heading"><div><p className="eyebrow">Evaluation lab</p><h1>Routing quality</h1></div><span>Reproducible, local benchmarks</span></div><div className="metric-grid"><article><strong>95%</strong><span>Mixed-language Top-3 baseline</span></article><article><strong>0</strong><span>Source files uploaded</span></article><article><strong>100</strong><span>Starter evaluation tasks</span></article></div><div className="empty-panel"><Pulse size={36} weight="duotone" /><h2>Run your first evaluation</h2><p>Import a JSONL dataset with task text and expected repositories. WhichRepo compares local retrieval with optional decision providers without sending full source code.</p><button>Choose dataset</button></div></section>; }
function SettingsView({ workspace }) { return <section className="content-view"><div className="content-heading"><div><p className="eyebrow">Settings & privacy</p><h1>Local by default</h1></div><span className="privacy"><ShieldCheck size={16} weight="fill" /> No telemetry</span></div><div className="settings-list"><article><div><h3>Workspace</h3><p>{workspace?.workspace || "Demo workspace"}</p></div><span>Indexed locally</span></article><article><div><h3>Language analyzers</h3><p>Go · TypeScript · Python · Java · Rust · .NET · PHP · Ruby</p></div><span>Pure-Go Tree-sitter</span></article><article><div><h3>Decision provider</h3><p>Local BM25 retrieval</p></div><span>Optional Jev enhancement</span></article><article><div><h3>Remote payload</h3><p>Task text, candidate summaries, and redacted evidence only</p></div><span>Preview before sending</span></article></div></section>; }

export function App() {
  const [view, setView] = useState("router"); const [projects, setProjects] = useState([]); const [workspace, setWorkspace] = useState(null);
  useEffect(() => { Promise.all([fetch("/api/projects"), fetch("/api/status")]).then(async ([projectsResponse, statusResponse]) => { if (projectsResponse.ok) setProjects(await projectsResponse.json()); if (statusResponse.ok) setWorkspace(await statusResponse.json()); }).catch(() => {}); }, []);
  const nav = [["router", MagnifyingGlass, "Router"], ["repositories", Folder, "Repositories"], ["evaluation", Pulse, "Evaluation"], ["settings", GearSix, "Settings"]];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><CirclesThreePlus size={28} weight="duotone" /><strong>WhichRepo</strong></div><nav>{nav.map(([id, Icon, label]) => <button key={id} className={view === id ? "active" : ""} onClick={() => setView(id)}><Icon size={21} weight={view === id ? "duotone" : "regular"} />{label}</button>)}</nav><div className="sidebar-footer"><span className="privacy"><LockSimple size={14} weight="fill" /> Local only</span><p>Your code stays on your machine.</p><small>Preview · Open source</small></div></aside><main>{view === "router" && <RouterView projects={projects} workspace={workspace} />}{view === "repositories" && <RepositoriesView projects={projects} />}{view === "evaluation" && <EvaluationView />}{view === "settings" && <SettingsView workspace={workspace} />}</main></div>;
}
